name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: winidows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/GraphQL.SQL.Builder.sln
    - name: Build
      run: dotnet build src/GraphQL.SQL.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test src/GraphQL.SQL.sln --no-build --verbosity normal --configuration Release
        
